### ISSUE TITLE
Connection to Git server fails for unknown reasons

### ISSUE THREAD

**Issue by icedream** [icedream/citizenmp-server-updater#11]
Awkward and confusing issue report from http://forum.citizen.re/t/citizenmp-server-updater-v1-1-0-linux-windows/559/38 - the reporter claims that the download fails (which effectively should terminate the program before build starts) but also says that the build itself fails.

Suggested causes:
- Firewall
- Temporary server downtime
- A recent breaking change in the Git server (tohjo.eu)
- A bug/malfunction in the LibGit2Sharp/libgit2 library

Last two causes are just guesses that I don't feel very confident about since no one else using this software has reported similar issues and on the test computers and VMs I have the software runs just as usual without issues.

Log:
```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> LibGit2Sharp.LibGit2SharpException: Failed to read data: The server returned an invalid or unrecognized response

   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_clone(String url, String workdir, GitCloneOptions& opts)
   at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath, CloneOptions options)
   at CitizenMP.Server.Installer.Program.Main(String[] args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Program.Main(String[] args)
```

**Comment by icedream** [comment]
Closing this as there have been no more reports on this.

**Comment by AndreyVaskovskiy** [comment]
The same issue when cloning large repository > 2GB. Error is gitlib2 api method git_clone.
